# Generated by Django 4.0.5 on 2022-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=50)),
                ('availability', models.BooleanField()),
                ('needing_repair', models.BooleanField()),
                ('durability', models.IntegerField()),
                ('max_durability', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('minimum_rent_period', models.IntegerField()),
            ],
        ),
    ]
