# Generated by Django 4.0.5 on 2022-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=127)),
                ('contact', models.CharField(max_length=512)),
                ('rent_period', models.IntegerField()),
                ('estimated_rent_fee', models.IntegerField()),
                ('is_returned', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
